version: 2.8.5.{build}
configuration: Release
platform: Any CPU
before_build:
- ps: >-
    $buildversion = New-Object System.Version($env:APPVEYOR_BUILD_VERSION)

    $v = New-Object System.Version($buildversion.Major, $buildversion.Minor, $buildversion.Build, ($buildversion.Revision - 18))


    $filepath = resolve-path ".\Properties\AssemblyInfo.cs"

    $content = (get-content -raw $filepath )

    $content = $content -replace "assembly: AssemblyVersion.*","assembly: AssemblyVersion(`"$v`")]"

    $content = $content -replace "assembly: AssemblyFileVersion.*","assembly: AssemblyFileVersion(`"$v`")]"

    set-content $filepath $content


    # change the version returned in nugetconstant

    $filepath = resolve-path ".\NugetLightConstant.cs"

    $content = (get-content -raw $filepath)

    $content = $content -replace "ProviderVersion.*;","ProviderVersion = `"$v`";"

    set-content $filepath $content


    $filepath = resolve-path  ".\provider.manifest"

    $content = (get-content -raw $filepath )

    $content = $content -replace "\s+version='.*'","    version='$v'"

    $content = $content -replace "uniqueId='.*'","uniqueId='nuget.$v'"

    $content = $content -replace "providerVersion='.*'","providerVersion='$v'"

    $content = $content -replace "href='.*'","href='https://oneget.org/Microsoft.PackageManagement.NuGetProvider-$v.dll'"

    set-content $filepath $content
build:
  verbosity: minimal
after_build:
- ps: >-
    $buildversion = New-Object System.Version($env:APPVEYOR_BUILD_VERSION)

    $version = New-Object System.Version($buildversion.Major, $buildversion.Minor, $buildversion.Build, ($buildversion.Revision - 18))


    Move-Item .\output\v45\Release\bin\Microsoft.PackageManagement.NuGetProvider.dll ".\output\v45\Release\bin\Microsoft.PackageManagement.NuGetProvider-$version.dll"

    Get-ChildItem .\output\v45\Release\bin\*-$version.dll | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName releasebits -Type Auto }
deploy: off
