version: 2.8.5.{build}
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
after_build:
- ps: >-
    $version = $env:APPVEYOR_BUILD_VERSION

    Move-Item .\output\v45\Release\bin\Microsoft.PackageManagement.NuGetProvider.dll ".\output\v45\Release\bin\Microsoft.PackageManagement.NuGetProvider-$version.dll"

    Get-ChildItem .\output\v45\Release\bin\*-$version.dll | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName releasebits -Type Auto }
deploy:
- provider: AzureBlob
  storage_account_name: oneget
  storage_access_key:
    secure: D09bvmFT5yslZgmyBBJZ772jQEt+PlTGN7/D0cwQrEECJNk049BOMPIPGigoYku6Z5r486dMxy02PUzGPApBD0V/dZCelNg5e4BQZE6I60b3nIzmsauOG7WEUluvcaeB
  container: providers
  artifact: releasebits
  unzip: true
  set_content_type: true
  on:
    branch: master
